# Generated by Django 3.0 on 2024-04-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240417_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='post/images/'),
            preserve_default=False,
        ),
    ]
