# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: category.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x61tegory.proto\x12\x08\x63\x61tegory\x1a\x1bgoogle/protobuf/empty.proto\":\n\x08\x43\x61tegory\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\x15\n\x13\x43\x61tegoryListRequest\"%\n\x17\x43\x61tegoryRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xb9\x02\n\x12\x43\x61tegoryController\x12=\n\x04List\x12\x1d.category.CategoryListRequest\x1a\x12.category.Category\"\x00\x30\x01\x12\x32\n\x06\x43reate\x12\x12.category.Category\x1a\x12.category.Category\"\x00\x12\x43\n\x08Retrieve\x12!.category.CategoryRetrieveRequest\x1a\x12.category.Category\"\x00\x12\x32\n\x06Update\x12\x12.category.Category\x1a\x12.category.Category\"\x00\x12\x37\n\x07\x44\x65stroy\x12\x12.category.Category\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'category_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CATEGORY']._serialized_start=57
  _globals['_CATEGORY']._serialized_end=115
  _globals['_CATEGORYLISTREQUEST']._serialized_start=117
  _globals['_CATEGORYLISTREQUEST']._serialized_end=138
  _globals['_CATEGORYRETRIEVEREQUEST']._serialized_start=140
  _globals['_CATEGORYRETRIEVEREQUEST']._serialized_end=177
  _globals['_CATEGORYCONTROLLER']._serialized_start=180
  _globals['_CATEGORYCONTROLLER']._serialized_end=493
# @@protoc_insertion_point(module_scope)
